### ISSUE TITLE
WARNING - Possible Scam Guide

### ISSUE THREAD

**Issue by BraapAround** [Giampetterson/LindaCoin-Masternode-Script#1]
# Warning from Linda Support Member
2 support people and the core team decided that this guide has some serious security issues. 
Do NOT use it.

**Comment by Giampetterson** [comment]
### **NO SCAM AT ALL** 
_I upload this conversation with this "NerdyGuy" to show how deep and sincere is his technical knowledge in explaining the problems and a possible solution_

This NerdyGuy pointed to me the following How-To:
- https://steemit.com/lindacoin/@auspex/how-to-setup-linda-for-staking-on-ubuntu-16-linux
- https://www.lindaprojectinfo.com/setting-up-a-vps/

These how-tos technically speaking are not:
- taking in consideration firewalling 
- taking in consideration TCP/IP v4 and v6 minimum hardening
- taking in consideration RPC "open to the world" as this NerdyGuys is claiming
- taking in consideration Backup/Recovery procedure for wallet

As stated, due my opensource and peer-review behaviour I stay here waiting for a technical conversation by which improve my code or make this 2 support guys to study a little bit.

Also, sadly, I have to observe that the problem is **_NOT_** my guide but the business that can be done freely to every Linux user in creating easily masternodes instead of MyStakingWallet. 

![1](https://user-images.githubusercontent.com/15069049/44686213-cdfe5100-aa4d-11e8-8a18-75e78bc00791.png)

![2](https://user-images.githubusercontent.com/15069049/44686219-d35b9b80-aa4d-11e8-9680-49d062dc679d.png)

![3](https://user-images.githubusercontent.com/15069049/44686227-d6ef2280-aa4d-11e8-83d9-996a33d9fc00.png)

**Comment by Giampetterson** [comment]
As expected,
I've not received **ANY** technical analysis from this NerdyGuy...just Nerdy right? 
When we have to talk with 0s and 1s the NerdyGuy stops...typical internet fanboy-lamer.

Anyway I close the issue due:

1. **this guy is NOT (yes! he's NOT) a Linda Coin Developer o Team Member** 
2. he deeply lacks of specific technical information
3. inability to prove an affirmation
4. probably the procedure, as published, is gnawing for this guy 
5. this guy will not receive much more Linda as he is asking in his "technical" white paper
6. technology does not work like the Inquisition (check the screenshot!)

If this guy will be able to produce appropriate technical information, we will open the issue again so that we can always find a solution to the problems that he will be able to demonstrate technically and not by copying/pasting.

**Comment by BraapAround** [comment]
Thank you for your comment. An official core team asked you to remove your guide and you didn't do it yet (7 days later) with turning this whole conversation on me. Your guide has been reviewed prior by an official Lindacoin core team member (developer) as by 2 support people who are programmers as profession. 

This result in that you're banned now from the Linda Discord.

As your printscreens doesn't containt the whole story, I love to add this last part to this conversation: 
![capture](https://user-images.githubusercontent.com/38507651/44999908-ed066100-afc0-11e8-90ff-cc60013ef0c6.PNG)

**Comment by JustinTether** [comment]
As a core member and owner of LindaProjects github organization I vouch for 'NerdyUser' both as a team member, developer (You can see his work on our git) as well as a trusted community member.

Your script is intentionally misleading in it's written form (coupled with an entirely wrong README.MD compared to code provided) and we do not endorse this behavior.

**Comment by Giampetterson** [comment]
Hello Justin,
seems that you have to talk also with Chris that in our italian community
said something different...anyway I'm not disrespectful to anyone because
the procedure I wrote may have some deficiencies but it was EXPLICITLY
asked to disclose them in order to improve it and make a contribution in
full open source conduct.

Besides all this just said, and given that you did not answer me on
Discord, I wrote procedures through which the operating system, the stack
tcp / ip and users, were a minimum structured in terms of security; these
aspects are NOT covered in any type of document issued or commented by
NerdyUser nor by the Linda community.

Therefore I reiterate my total availability to the technical / scientific
discussion and, in the same way, I stress my total distance from
communications that have no technical, scientific basis but that are issued
ex-cathedra in a context in which this type of form should be totally
non-existent.

I have tried to say to "NerdyUser" that I respects your work but I do not
tolerate any preconceived analytical conceptualizations that are similar to
adolescent thoughts and outside of any professionalism or pragmatic
documented data.

Therefore the guide stays online until your respectable attitude, however,
does not publicly represent the mistakes I made in the guide itself.

With best regards
Giampaolo



Il giorno lun 3 set 2018 alle ore 22:52 Justin Tether <
notifications@github.com> ha scritto:

**Comment by Giampetterson** [comment]
you are right, no problem in adding the WHOLE story; I'm totally open
in constructive conversations...and by facts I don't have to need to hide
something.
Giampa

Il giorno lun 3 set 2018 alle ore 21:34 NerdyUser <notifications@github.com>
ha scritto:
